export default {
  appName: "Simalytics",
  packageName: "@kyter/simalytics-ios",
  bundleId: "com.kyter.simalytics",
  appId: "6745519450",
  platform: "IOS",
  locale: "en-US",
  xcodeCloudWorkflowId: "4D2E22C1-0C54-4F04-9007-226B9FCE4734",
  xcodeProject: "simalytics.xcodeproj/project.pbxproj",
  appStoreMetadataPath: "marketing/app-store-metadata",
  appStorePrivacyPath: "marketing/app-store-privacy/privacy.json",
  releaseHistoryPath: "docs/apple-release-history.md",
  nextReleaseNotesPath: "docs/next-release-notes.md",
  gitTagPrefix: "simalytics-ios@",
  commitSyntax: "conventional",
};
